### ISSUE TITLE
Time is not expanded as expected on RSS/RO

### ISSUE THREAD

**Issue by macluky** [Aelfhe1m/Historian-Expanded#33]
Hi,
My config is:

	SITUATION_TEXT
	{
		Anchor = 0.0,0.5
		Position = 0.25,0.9
		Size = 0.5,0.125
		Color = 1.0,1.0,1.0,1.0
		TextAnchor = MiddleLeft
		FontSize = 14
		FontStyle = Normal
		Default = <b><UT></b><N><T+><N><Custom>
		Landed = <size=21><b><Vessel></b></size><N>Landed on <Body>’s <LandingZone> at <Latitude>ºN, <Longitude>ºW<N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		Splashed = <size=21><b><Vessel></b></size><N>Splashed down in <Body>’s waters at <Latitude>ºN, <Longitude>ºW<N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		Prelaunch = <size=21><b><Vessel></b></size><N>Preparing for launch from <Body> at <Latitude>ºN, <Longitude>ºW<N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		Flying = <size=21><b><Vessel></b></size><N>Flying Mach <Mach> (<Speed>) <Altitude> over <Body>’s <Biome> at <Latitude>ºN, <Longitude>ºW<N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		SubOrbital = <size=21><b><Vessel></b></size><N>On a sub-orbital trajectory <Altitude> over <Body>’s <Biome><N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		Orbiting = <size=21><b><Vessel></b></size><N>Orbiting <Altitude> above <Body><N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		Escaping = <size=21><b><Vessel></b></size><N>Escaping from <Body> at <Speed><N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
		Docked = <size=21><b><Vessel></b></size><N>Docked <Altitude> above <Body>’s <Biome><N><size=12>ME<T+> </size><size=10>(<UT>) <Crew></size><N><Custom>
	}

 But the date does not seem to expand as expected:
![screenshot_2021-01-23--02-30-19](https://user-images.githubusercontent.com/3543145/105769376-0592bf80-5f5e-11eb-8b83-572a040af347.png)
[Chris.layout.log](https://github.com/Aelfhe1m/Historian-Expanded/files/5869811/Chris.layout.log)

Installed through CKAN Module info:- version:	2:v1.8.0

**Comment by Aelfhe1m** [comment]
Intended behaviour. That layout is using <UT> tag which shows year and day numbers. There are separate <DATE> and <DATEKAC> tags for formatted dates ([documentation](https://github.com/Aelfhe1m/Historian-Expanded/blob/master/Documentation/Tags-Dates.md)).
